In [16]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv("../data/datasets/new york/new york.csv")
df.rename(columns={"ts": "timestamp"}, inplace=True)
df.rename(columns={"app_temp": "feels_like",
                 "clouds": "clouds_percentage", "elev_angle": "sun_horison_angle",
                 "precip": "precipitation", "pres": "pressure",
                 "rh": "humidity", "snow": "snow_level",
                 "vis": "visibility", "wind_spd": "wind_speed",
                 "wind_dir": "wind_direction"}, inplace=True)
df = df[['timestamp', 'temp', 'feels_like', 'clouds_percentage', 'sun_horison_angle',
         'precipitation', 'pressure', 'humidity', 'snow_level', 'visibility',
         'wind_speed', 'wind_direction', 'weather_description']]
df.head(5)

,timestamp,temp,feels_like,clouds_percentage,sun_horison_angle,precipitation,pressure,humidity,snow_level,visibility,wind_speed,wind_direction,weather_description
0,1393632000,-5.1,-6.9,0,-14.7,0.0,1029,48,0.0,NaN,1.2,232,Clear Sky
1,1393635600,-5.4,-7.3,0,-25.9,0.0,1029,52,0.0,NaN,1.2,220,Clear Sky
2,1393639200,-5.4,-7.3,0,-36.6,0.0,1030,59,0.0,NaN,1.2,264,Clear Sky
3,1393642800,-5.7,-6.5,0,-46.2,0.0,1030,59,0.0,NaN,0.8,266,Clear Sky
4,1393646400,-5.8,-5.0,0,-53.4,0.0,1030,66,0.0,NaN,0.4,266,Clear Sky

In [26]:
min_timestamp = df['timestamp'].min()
df['from_0_ts'] = df['timestamp'] - min_timestamp

In [27]:
num_s_day = 60*60*24
num_s_year = 365.2425* num_s_day
df["day_sin"] = np.sin(df['from_0_ts'] * (2 * np.pi / num_s_day))
df["day_cos"] = np.cos(df['from_0_ts'] * (2 * np.pi / num_s_day))

df["year_sin"] = np.sin(df['from_0_ts'] * (2 * np.pi / num_s_year))
df["year_cos"] = np.cos(df['from_0_ts'] * (2 * np.pi / num_s_year))

In [28]:

df.drop(columns=['from_0_ts'], inplace=True)
df.head(5)

,timestamp,temp,feels_like,clouds_percentage,sun_horison_angle,precipitation,pressure,humidity,snow_level,visibility,wind_speed,wind_direction,weather_description,day_sin,day_cos,year_sin,year_cos
0,1393632000,-5.1,-6.9,0,-14.7,0.0,1029,48,0.0,NaN,1.2,232,Clear Sky,0.000000,1.000000,0.000000,1.000000
1,1393635600,-5.4,-7.3,0,-25.9,0.0,1029,52,0.0,NaN,1.2,220,Clear Sky,0.258819,0.965926,0.000717,1.000000
2,1393639200,-5.4,-7.3,0,-36.6,0.0,1030,59,0.0,NaN,1.2,264,Clear Sky,0.500000,0.866025,0.001434,0.999999
3,1393642800,-5.7,-6.5,0,-46.2,0.0,1030,59,0.0,NaN,0.8,266,Clear Sky,0.707107,0.707107,0.002150,0.999998
4,1393646400,-5.8,-5.0,0,-53.4,0.0,1030,66,0.0,NaN,0.4,266,Clear Sky,0.866025,0.500000,0.002867,0.999996

In [29]:
df.drop(columns=['snow_level'], inplace=True)
df.drop(columns=['visibility'], inplace=True)

In [30]:
df.index = df["timestamp"]

In [31]:
df.drop(columns=["timestamp"], inplace=True)

In [32]:
df.to_csv('../data/datasets/new york/new york.csv')